name: Publish NuGet Mvc
 
on:
  push:
    branches: [ master ]
    paths: [ 'src/**' ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/Localization.Mvc/Localization.Mvc.csproj 
      
    - name: Build
      run: dotnet build --no-restore src/Localization.Mvc/Localization.Mvc.csproj 
        
    - name: Package
      run: dotnet pack -c Release -o . src/Localization.Mvc/Localization.Mvc.csproj 
      
    - name: Publish on NuGet
      run: dotnet nuget push ./*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
